name: actions secret
on:
  workflow_dispatch:
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: check secret is set
        run: |
          if [ -z "$my_secret" ]; then
            echo "Secret is NOT set"
          else
            echo "Secret is set"
          fi
        env:
          my_secret: ${{ secrets.my_top_secret }}
