name: actions secret
on:
  workflow_dispatch:

jobs:
  deplyment:
    runs-on: ubuntu-latest
    steps:
      - name: print secret
        run: |
          echo " my-top-secret is : ${{secrets.my_top_secret}} " 

      - name: print my secret as environment variable
        run: |
          echo " my-top-secret is : $my_secret "
        env:
          my_secret : ${{secrets.my_top_secret}}
